apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-v2
  namespace: cinema
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: catalog-service
      version: v2
  template:
    metadata:
      labels:
        app: catalog-service
        version: v2
    spec:
      containers:
      - name: catalog-service
        image: cinema.moviecatalog:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3